cities:
  - name: "Lahore"
    lat: 31.5497
    lon: 74.3436
  - name: "Karachi"
    lat: 24.8607
    lon: 67.0011
  - name: "Islamabad"
    lat: 33.6844
    lon: 73.0479
  - name: "Faisalabad"
    lat: 31.4504
    lon: 73.1350
  - name: "Multan"
    lat: 30.1575
    lon: 71.5249
  - name: "Peshawar"
    lat: 34.0151
    lon: 71.5805
  - name: "Rawalpindi"
    lat: 33.5651
    lon: 73.0169
  - name: "Gujranwala"
    lat: 32.1877
    lon: 74.1945