[theme]
base = "dark"
primaryColor = "#00E400"
backgroundColor = "#080c14"
secondaryBackgroundColor = "#101726"
textColor = "#f1f5f9"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
